# 원본 엑셀(PT.SAMJIN Reliability Test Item) 7개 시트에서 추출한 제품군별 표준 템플릿 시드 데이터

# 제품군 순서 (표시 순서)
PRODUCT_GROUPS = [
    "리모컨/IoT",
    "스피커",
    "HUB V4(IoT)",
    "BLE Tag(IoT)",
    "고무(Rubber)",
    "사출(Injection)",
]

# 각 항목 필드: seq, category, item_name, code, spec, criteria, qty, days, available, remark
# available 은 고무/사출처럼 자체 수행가능 여부가 명시된 경우만 사용.
TEMPLATE_ITEMS = {
    "리모컨/IoT": [
        (1, "Essential", "Vibration ( Box ) - Common", "VB1",
         "Freq 10-55-10Hz, Amplitude 0.85Grms, Sweep Mode duration 6 hr",
         "APP:O / FT:O", "5", "1", "", ""),
        (1, "Essential", "Vibration ( Box ) - BLE Tag (IoT)", "VB2",
         "0.59 Grms / 3~200 Hz Random Mode, Y-Axis 6Hrs",
         "APP:O / FT:O", "5", "1", "", "New Product"),
        (2, "Essential", "Drop Box - Common", "DR",
         "1 angle, 3 ridges, 6 sides, Steel floor / distance 0.6m (height varies by weight)",
         "APP:O / FT:O", "1 Box", "1", "", ""),
        (2, "Essential", "Drop Test1 ( Set ) - Common VD", "DR1",
         "Down on concrete floor, High 1.5M, Free fall (6-sided)",
         "APP:O / FT:O", "5", "1", "", ""),
        (2, "Essential", "Drop Test2 ( Set ) - Common VD", "DR2",
         "Power on/off during Drop: high 30~40cm, Set Power On -> Drop -> Check TV",
         "FT:O", "-", "-", "", "new item (y26~)"),
        (2, "Essential", "Drop Test1 ( Set ) - AC", "DR3",
         "Down on Wooden Board, High 1.0M, Free fall (3-sided), 5x sequence: Battery -> Window -> Left side",
         "APP:O / FT:O", "5", "1", "", ""),
        (2, "Essential", "Drop Test1 ( Set ) - Hub V4(IoT)", "DR4",
         "Down on concrete floor, High 0.7M, Free fall (6-sided) x2 times",
         "APP:O / FT:O", "1", "1", "", "New Product"),
        (3, "Essential", "Chamber / Humidity [ Set ]", "CH1",
         "Temp 60±5℃, Humidity 90~95%, 96 hr",
         "APP:O / FT:O", "5", "4", "", ""),
        (3, "Essential", "Storage Test [ CKD / Single ]", "SR1",
         "Temp -30℃/+60℃, 60~90%, Total 2 cycles 75Hr (37.5 Hr/Cycle)",
         "APP:O", "1 Box", "3", "", ""),
        (3, "Essential", "Storage Test [ Dev-Set ] - RCU", "SR1",
         "Temp -30℃/+60℃, 60~90%, Total 5 cycles 187.5Hr (37.5 Hr/Cycle)",
         "APP:O / FT:O", "", "8", "", ""),
        (3, "Essential", "Storage Test - IoT Product", "SR2",
         "Temp -30~60℃, 90%, Total 1 cycle 52Hr",
         "APP:O / FT:O", "", "2", "", ""),
        (4, "Conditional", "Cold Chamber", "CL",
         "Temp -20±5℃, Humidity 0%, 96 hr",
         "APP:O / FT:O", "3", "4", "", ""),
        (5, "Conditional", "Hot Chamber", "HT",
         "Temp 60±5℃, Humidity 0%, 96 hr",
         "APP:O / FT:O", "3", "4", "", ""),
        (6, "Conditional", "Eraser Test - Common", "AB",
         "Load 500g, Ethanol 100 cycle & non, Spec 2,000 cycle (round trips)",
         "APP:O", "3", "2", "", "Update / review"),
        (6, "Essential", "Eraser Test - BLE Tag (IoT)", "AB-1",
         "Load 500g, Spec 1,000 cycle (round trips)",
         "APP:O", "3", "2", "", "New Product"),
        (7, "Conditional", "Liquid Inflow", "LS",
         "Liquid: Coffee (1/3 cup), inlet Top Case surface, Left 24 Hr",
         "FT:O", "2", "1", "", ""),
        (8, "Essential", "Aging Test - HUB V4(IoT)", "AT",
         "On boarding Test, Set Standby on Room Temperature, 24 hr",
         "FT:O", "3", "1", "", "New Product"),
    ],
    "스피커": [
        (0, "Initial", "Initial Test - Normal test ( OQC )", "",
         "Normal test (OQC)",
         "Audio:O / Freq:O / Impedance:O / SPL:O", "20", "-", "", ""),
        (1, "Essential", "Vibration Box", "VB1",
         "Amplitude 1.5mm / Frequency 10-55-10Hz, 6hrs Y-Axis",
         "Audio:O / Freq:O / Impedance:O / SPL:O", "20", "1", "", ""),
        (2, "Essential", "Chamber Low (Cold)", "CL",
         "Cold Chamber -20℃, Humidity 0%, 96 hr",
         "Audio:O / Freq:O / Impedance:O / SPL:O", "3", "4", "", ""),
        (3, "Essential", "Chamber High (Hot)", "CH",
         "Hot Chamber 60±5℃, Humidity 0%, 96 hr",
         "Audio:O / Freq:O / Impedance:O / SPL:O", "3", "4", "", ""),
        (4, "Essential", "Chamber Humidity", "CH2",
         "Temp 40±5℃, Humidity 90~95%, 96 hr",
         "Audio:O / Freq:O / Impedance:O / SPL:O", "3", "4", "", "MP New-Mold"),
        (5, "Essential", "Voice Destructive Test", "Voice",
         "RMS 100% (7.75 Volt), input Tone 400Hz, 15 hr",
         "Audio:O / Freq:O / Impedance:O / SPL:O", "4", "1", "", ""),
        (6, "Essential", "Continuous Load / Durability Test", "Load",
         "RMS 100% (7.75 Volt), Freq 20-20k 3sec 0.2term sweep, Total 96 hr",
         "Audio:O / Freq:O / Impedance:O / SPL:O", "10", "4", "", "PR 10EA / MP 4EA"),
        (0, "Note", "Drop Test", "",
         "HQ > Not Recommended", "", "", "", "", "제외 권고"),
    ],
    "HUB V4(IoT)": [
        (1, "Distribution / Environment", "Vibration Test (Carton)", "",
         "Amplitude 1.5mm / Frequency 10-55-10Hz, 6hrs Y-Axis",
         "Vibration Environment / Packaging Durability", "1 Carton (48EA)", "1", "", ""),
        (1, "Distribution / Environment", "Drop Test (Carton)", "",
         "Height: Bottom 65cm, other 40cm, 1 corner 3 abilities 6 sides",
         "Transport and Handling Stability", "1 Carton (48EA)", "1", "", ""),
        (1, "Distribution / Environment", "Drop Test (Product)", "",
         "Height 70cm, position 6 sides, 2 times",
         "Transport and Handling Stability", "1 EA", "1", "", ""),
        (2, "Environment", "Storage Cycle Test", "",
         "-30~60℃, 90%, 52hrs / 1 cycle, with load 68Kg, total 52hr",
         "Multi-Stack Load Resistance", "1 Carton (48EA)", "3", "", ""),
        (2, "Environment", "Aging Test", "",
         "On boarding Test, Set Standby on Room Temperature, 24 hr",
         "Long-term performance and durability", "3 EA", "1", "", ""),
    ],
    "BLE Tag(IoT)": [
        (1, "Distribution / Environment", "Vibration Test (Carton)", "",
         "0.59 Grms / 3~200 Hz Random Mode, Y-Axis 3Hrs",
         "Vibration Environment / Packaging Durability", "1 Carton (240EA)", "1", "", ""),
        (1, "Distribution / Environment", "Drop Test (Carton)", "",
         "91cm (<10kg), 1 angle, 3 ridges, 5 sides, Steel floor",
         "Transport and Handling Stability", "1 Carton (240EA)", "1", "", ""),
        (2, "Durability", "Rubbing Test / Eraser", "",
         "Rub printed area 1,000 cycles, Dai-maru fabric under 500g load",
         "Label / print readability", "3 EA", "1", "", ""),
        (3, "Environment", "Storage Cycle Test", "",
         "-30~60℃, 90%, 52hrs / 1 cycle, with load around 29Kg (8-layer)",
         "Multi-Stack Load Resistance", "1 Carton (240EA)", "3", "", ""),
    ],
    "고무(Rubber)": [
        (1, "Environment", "High temperature / storage", "",
         "After leaving at 60℃ for 168 hours, leave at room temperature for 30 minutes",
         "No operational / external defects (deformation, detachment, damage, cracking)",
         "5EA", "7", "Possible", ""),
        (2, "Environment", "Low temperature / storage", "",
         "After leaving at -20℃ for 168 hours, leave at room temperature for 30 minutes",
         "No operational / external defects (deformation, detachment, damage, cracking)",
         "5EA", "7", "Possible", ""),
        (3, "Environment", "Temperature / Humidity", "",
         "168 hours at 60℃ and 95% humidity, then room temperature for 12 hours",
         "No operational / external defects (deformation, detachment, damage, cracking)",
         "5EA", "7", "Possible", ""),
        (4, "Environment", "Thermal shock", "",
         "-20℃ 30min, 60℃ 30min = 1 cycle, 100 ~ 1,000 Cycles, then room temp 1 hour",
         "No operational / external defects (deformation, detachment, damage, cracking)",
         "5EA", "7", "can't", "no chamber"),
        (5, "Packing", "Packing / Vibration", "",
         "Frequency 10-55-10Hz, Sweep time 6hr, Direction X-axis, Amplitude 1.5mm",
         "No operational / external defects (deformation, detachment, damage, cracking)",
         "1 Box", "1", "Possible", ""),
        (6, "Durability", "Wear / Resistance", "",
         "Standard 2,000 cycles; Alcohol: ethylene alcohol 99.9%, 100 cycles, 500g load",
         "Print must be legible (must not fade)",
         "각 2EA", "1", "Possible", ""),
        (7, "Durability", "Operating life", "",
         "Dome Switch 100,000 cycles, Load 1kg.f",
         "No operational issues; no defects on disassembly; no battery leakage/ignition/overheating/swelling",
         "2EA", "1", "can't", "no equipment"),
    ],
    "사출(Injection)": [
        (1, "Environment", "High temperature / storage", "",
         "After leaving at 60℃ for 168 hours, leave at room temperature for 30 minutes",
         "No operational / external defects (deformation, detachment, damage, cracking)",
         "5EA", "7", "Possible", ""),
        (2, "Environment", "Low temperature / storage", "",
         "After leaving at -20℃ for 168 hours, leave at room temperature for 30 minutes",
         "No operational / external defects (deformation, detachment, damage, cracking)",
         "5EA", "7", "Possible", ""),
        (3, "Environment", "Temperature / Humidity", "",
         "168 hours at 60℃ and 95% humidity, then room temperature for 12 hours",
         "No operational / external defects (deformation, detachment, damage, cracking)",
         "5EA", "7", "Possible", ""),
        (4, "Environment", "Thermal shock", "",
         "-20℃ 30min, 60℃ 30min = 1 cycle, 100 ~ 1,000 Cycles, then room temp 1 hour",
         "No operational / external defects (deformation, detachment, damage, cracking)",
         "5EA", "7", "can't", "no chamber"),
        (5, "Packing", "Packing / Vibration", "",
         "Frequency 10-55-10Hz, Sweep time 6hr, Direction X-axis, Amplitude 1.5mm",
         "No operational / external defects (deformation, detachment, damage, cracking)",
         "1 Box", "1", "Possible", ""),
        (6, "Durability", "General / Single Item Drop", "",
         "1.5M, steel plate, 6 sides (1 time) free fall",
         "No operational issues; reassemble if exterior cracks or separates",
         "5EA", "1", "Possible", ""),
        (7, "Durability", "Continue / Single Drop", "",
         "50cm, Steel Plate, Random 1,000 times (Solar Cell / Secondary Battery model)",
         "No operational issues; reassemble if exterior cracks or separates",
         "2EA", "1", "can't", "no equipment"),
        (8, "Durability", "Human / Body weight", "",
         "Human load 80kg (shoes removed), battery location (Front/Rear) 5 seconds x10 times",
         "No operational issues; no defects on disassembly; no battery leakage/ignition/overheating/swelling",
         "2EA", "1", "-", "secondary battery model"),
        (9, "Durability", "Wear / Resistance", "",
         "Standard 2,000 cycles; Alcohol: ethylene alcohol 99.9%, 100 cycles, 500g load",
         "Print must be legible (must not fade)",
         "각 2EA", "1", "Possible", ""),
        (10, "Durability", "Operating life", "",
         "Dome Switch 100,000 cycles, Load 1kg.f",
         "No operational issues; no defects on disassembly; no battery leakage/ignition/overheating/swelling",
         "2EA", "1", "can't", "no equipment"),
        (11, "Chemical", "Chemical Resistance", "",
         "", "", "", "", "-", ""),
    ],
}

# 개발 단계 옵션 (모델 단위)
DEV_STAGES = ["PR", "SR", "MP", "OQC"]

# 시험항목별 State 옵션 (항목 단위 드롭다운)
ITEM_STAGES = ["PV", "PR", "SR", "MP"]

# 진행 상태 옵션
PROGRESS_STATES = ["계획", "진행", "완료", "보류", "해당없음"]

# 판정 결과 옵션
RESULTS = ["-", "OK", "NG"]
